registry:
  registry_store_type: feast_azure_provider.registry_store.AzBlobRegistryStore
  path: "https://myfeastregistry.blob.core.windows.net/feast/registry-teste-dm.db" # "https://myfeastregistry.blob.core.windows.net/feast/registry.db"
project: datamaster_teste
provider: local
online_store:
    type: redis
    connection_string: "myfeastonline.redis.cache.windows.net:6379,password=vuTBnjj0ISx3GbbbgY4oDb14LYhyEVgMBAzCaIYba4k="
offline_store:
    type: spark # will use the active SparkSession